name: CI

on:
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        env:
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
            BASE_BRANCH: ${{ github.base_ref }}
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"

            - name: Extract out parent branch
              shell: bash
              run: echo "##[set-output name=parent_branch;]$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')"
              id: extract_parent_branch

            - name: Install dependencies
              run: yarn

            - name: Lint, test and build (push)
              if: ${{ github.event_name == 'push' }}
              run: yarn turbo run build --since=${{ steps.extract_parent_branch.outputs.parent_branch }}

            - name: Lint, test and build (pull request)
              if: ${{ github.event_name == 'pull_request' }}
              run: yarn turbo run build --since=origin/${{ env.BASE_BRANCH }}
